/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:beeedfe4-e0d2-45cb-baf0-c546737457b8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_eAgJHewcw",
    "aws_user_pools_web_client_id": "1nptl7hp70s4u4d875bku0ud1j",
    "oauth": {}
};


export default awsmobile;
